### ISSUE TITLE
login status is confused on ng firebase:init

### ISSUE THREAD

**Issue by rwillmer** [davideast/angular-cli-firebase-hosting#3]
$ firebase login
    Already logged in as <email>

    $ ng firebase:init
    { [FirebaseError: Command requires authentication, please run firebase login]
      name: 'FirebaseError',
      message: 'Command requires authentication, please run \u001b[1mfirebase login\u001b[22m',
      children: [],
      status: 500,
      exit: 1,
      stack: 'Error\n    at Error.FirebaseError
        (.../node_modules/firebase-tools/lib/error.js:11:17)\n    at module.exports
        (.../node_modules/firebase-tools/lib/requireAuth.js:32:7)\n    at ../node_modules/firebase-tools/lib/command.js:127:25\n    at lib$rsvp$$internal$$tryCatch 
        (.../node_modules/rsvp/dist/rsvp.js:1036:16)\n    at lib$rsvp$$internal$$invokeCallback 
        (.../node_modules/rsvp/dist/rsvp.js:1048:17)\n    at .../node_modules/rsvp/dist/rsvp.js:331:11\n    at lib$rsvp$asap$$flush
        (.../node_modules/rsvp/dist/rsvp.js:1198:9)\n    at nextTickCallbackWith0Args (node.js:420:9)\n    at process._tickCallback (node.js:349:13)',
    original: undefined,
    context: undefined }`

**Comment by rwillmer** [comment]
Turns out that just using the standard firebase init/deploy works fine... So I'm not sure what the purpose of this repo is? could you enlighten me please?

**Comment by Splaktar** [comment]
It seems out of date and possibly no longer needed.
