### ISSUE TITLE
 ng firebase:init Shows Error.

### ISSUE THREAD

**Issue by aashirjaved** [davideast/angular-cli-firebase-hosting#4]
{ Error: Command failed: ng build --environment=production
Environment "production" does not exist.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ng build --environment=production' }

**Comment by davideast** [comment]
Hey @aashirjaved! I should put an obsolete notice on this repo. It's way out of date and it's too easy to setup Firebase Hosting without a helper command. You just need to set "dist" as your public directory when doing `firebase init` and then simply do `firebase deploy`.
